name: opengraph
description: A Dart/Flutter package for seamless integration of OpenGraph metadata, allowing easy display of website information via API.
version: 0.0.14
homepage: https://datogedon.com
license: MIT
repository: https://github.com/baldomerocho/flutter_opengraph
issue_tracker: https://github.com/baldomerocho/flutter_opengraph/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2

flutter:
  assets:
    - assets/notfound.jpeg

