name: opengraph
description: OpenGraph
version: 0.0.7
homepage: https://datogedon.com
license: MIT
github: https://github.com/baldomerocho/flutter_opengraph

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2

flutter:

